/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthShareTokenRouteImport } from './routes/health-share/$token'
import { Route as ApiSleepRouteImport } from './routes/api/sleep'
import { Route as ApiNutritionRouteImport } from './routes/api/nutrition'
import { Route as ApiMedverifyRouteImport } from './routes/api/medverify'
import { Route as ApiFitnessSuggestionRouteImport } from './routes/api/fitness-suggestion'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSleepRouteImport } from './routes/_authenticated/sleep'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedHydrationRouteImport } from './routes/_authenticated/hydration'
import { Route as AuthenticatedHealthVaultRouteImport } from './routes/_authenticated/health-vault'
import { Route as AuthenticatedFitnessRouteImport } from './routes/_authenticated/fitness'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedClockRouteImport } from './routes/_authenticated/clock'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiHealthShareTokenRouteImport } from './routes/api/health-share/$token'
import { Route as AuthenticatedTrackersVitalsRouteImport } from './routes/_authenticated/trackers.vitals'
import { Route as AuthenticatedFindHospitalsRouteImport } from './routes/_authenticated/find.hospitals'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthShareTokenRoute = HealthShareTokenRouteImport.update({
  id: '/health-share/$token',
  path: '/health-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSleepRoute = ApiSleepRouteImport.update({
  id: '/api/sleep',
  path: '/api/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionRoute = ApiNutritionRouteImport.update({
  id: '/api/nutrition',
  path: '/api/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedverifyRoute = ApiMedverifyRouteImport.update({
  id: '/api/medverify',
  path: '/api/medverify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFitnessSuggestionRoute = ApiFitnessSuggestionRouteImport.update({
  id: '/api/fitness-suggestion',
  path: '/api/fitness-suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSleepRoute = AuthenticatedSleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHydrationRoute = AuthenticatedHydrationRouteImport.update({
  id: '/hydration',
  path: '/hydration',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthVaultRoute =
  AuthenticatedHealthVaultRouteImport.update({
    id: '/health-vault',
    path: '/health-vault',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFitnessRoute = AuthenticatedFitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClockRoute = AuthenticatedClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiHealthShareTokenRoute = ApiHealthShareTokenRouteImport.update({
  id: '/api/health-share/$token',
  path: '/api/health-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrackersVitalsRoute =
  AuthenticatedTrackersVitalsRouteImport.update({
    id: '/trackers/vitals',
    path: '/trackers/vitals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFindHospitalsRoute =
  AuthenticatedFindHospitalsRouteImport.update({
    id: '/find/hospitals',
    path: '/find/hospitals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app': typeof AuthenticatedAppRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/clock': typeof AuthenticatedClockRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/fitness': typeof AuthenticatedFitnessRoute
  '/health-vault': typeof AuthenticatedHealthVaultRoute
  '/hydration': typeof AuthenticatedHydrationRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sleep': typeof AuthenticatedSleepRoute
  '/store': typeof AuthenticatedStoreRoute
  '/api/chat': typeof ApiChatRoute
  '/api/fitness-suggestion': typeof ApiFitnessSuggestionRoute
  '/api/medverify': typeof ApiMedverifyRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/sleep': typeof ApiSleepRoute
  '/health-share/$token': typeof HealthShareTokenRoute
  '/find/hospitals': typeof AuthenticatedFindHospitalsRoute
  '/trackers/vitals': typeof AuthenticatedTrackersVitalsRoute
  '/api/health-share/$token': typeof ApiHealthShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app': typeof AuthenticatedAppRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/clock': typeof AuthenticatedClockRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/fitness': typeof AuthenticatedFitnessRoute
  '/health-vault': typeof AuthenticatedHealthVaultRoute
  '/hydration': typeof AuthenticatedHydrationRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sleep': typeof AuthenticatedSleepRoute
  '/store': typeof AuthenticatedStoreRoute
  '/api/chat': typeof ApiChatRoute
  '/api/fitness-suggestion': typeof ApiFitnessSuggestionRoute
  '/api/medverify': typeof ApiMedverifyRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/sleep': typeof ApiSleepRoute
  '/health-share/$token': typeof HealthShareTokenRoute
  '/find/hospitals': typeof AuthenticatedFindHospitalsRoute
  '/trackers/vitals': typeof AuthenticatedTrackersVitalsRoute
  '/api/health-share/$token': typeof ApiHealthShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/clock': typeof AuthenticatedClockRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/fitness': typeof AuthenticatedFitnessRoute
  '/_authenticated/health-vault': typeof AuthenticatedHealthVaultRoute
  '/_authenticated/hydration': typeof AuthenticatedHydrationRoute
  '/_authenticated/medications': typeof AuthenticatedMedicationsRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sleep': typeof AuthenticatedSleepRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/api/chat': typeof ApiChatRoute
  '/api/fitness-suggestion': typeof ApiFitnessSuggestionRoute
  '/api/medverify': typeof ApiMedverifyRoute
  '/api/nutrition': typeof ApiNutritionRoute
  '/api/sleep': typeof ApiSleepRoute
  '/health-share/$token': typeof HealthShareTokenRoute
  '/_authenticated/find/hospitals': typeof AuthenticatedFindHospitalsRoute
  '/_authenticated/trackers/vitals': typeof AuthenticatedTrackersVitalsRoute
  '/api/health-share/$token': typeof ApiHealthShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app'
    | '/appointments'
    | '/assistant'
    | '/clock'
    | '/emergency'
    | '/fitness'
    | '/health-vault'
    | '/hydration'
    | '/medications'
    | '/nutrition'
    | '/profile'
    | '/records'
    | '/schedule'
    | '/settings'
    | '/sleep'
    | '/store'
    | '/api/chat'
    | '/api/fitness-suggestion'
    | '/api/medverify'
    | '/api/nutrition'
    | '/api/sleep'
    | '/health-share/$token'
    | '/find/hospitals'
    | '/trackers/vitals'
    | '/api/health-share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app'
    | '/appointments'
    | '/assistant'
    | '/clock'
    | '/emergency'
    | '/fitness'
    | '/health-vault'
    | '/hydration'
    | '/medications'
    | '/nutrition'
    | '/profile'
    | '/records'
    | '/schedule'
    | '/settings'
    | '/sleep'
    | '/store'
    | '/api/chat'
    | '/api/fitness-suggestion'
    | '/api/medverify'
    | '/api/nutrition'
    | '/api/sleep'
    | '/health-share/$token'
    | '/find/hospitals'
    | '/trackers/vitals'
    | '/api/health-share/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/app'
    | '/_authenticated/appointments'
    | '/_authenticated/assistant'
    | '/_authenticated/clock'
    | '/_authenticated/emergency'
    | '/_authenticated/fitness'
    | '/_authenticated/health-vault'
    | '/_authenticated/hydration'
    | '/_authenticated/medications'
    | '/_authenticated/nutrition'
    | '/_authenticated/profile'
    | '/_authenticated/records'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/sleep'
    | '/_authenticated/store'
    | '/api/chat'
    | '/api/fitness-suggestion'
    | '/api/medverify'
    | '/api/nutrition'
    | '/api/sleep'
    | '/health-share/$token'
    | '/_authenticated/find/hospitals'
    | '/_authenticated/trackers/vitals'
    | '/api/health-share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFitnessSuggestionRoute: typeof ApiFitnessSuggestionRoute
  ApiMedverifyRoute: typeof ApiMedverifyRoute
  ApiNutritionRoute: typeof ApiNutritionRoute
  ApiSleepRoute: typeof ApiSleepRoute
  HealthShareTokenRoute: typeof HealthShareTokenRoute
  ApiHealthShareTokenRoute: typeof ApiHealthShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-share/$token': {
      id: '/health-share/$token'
      path: '/health-share/$token'
      fullPath: '/health-share/$token'
      preLoaderRoute: typeof HealthShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sleep': {
      id: '/api/sleep'
      path: '/api/sleep'
      fullPath: '/api/sleep'
      preLoaderRoute: typeof ApiSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition': {
      id: '/api/nutrition'
      path: '/api/nutrition'
      fullPath: '/api/nutrition'
      preLoaderRoute: typeof ApiNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medverify': {
      id: '/api/medverify'
      path: '/api/medverify'
      fullPath: '/api/medverify'
      preLoaderRoute: typeof ApiMedverifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fitness-suggestion': {
      id: '/api/fitness-suggestion'
      path: '/api/fitness-suggestion'
      fullPath: '/api/fitness-suggestion'
      preLoaderRoute: typeof ApiFitnessSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sleep': {
      id: '/_authenticated/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof AuthenticatedSleepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hydration': {
      id: '/_authenticated/hydration'
      path: '/hydration'
      fullPath: '/hydration'
      preLoaderRoute: typeof AuthenticatedHydrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health-vault': {
      id: '/_authenticated/health-vault'
      path: '/health-vault'
      fullPath: '/health-vault'
      preLoaderRoute: typeof AuthenticatedHealthVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fitness': {
      id: '/_authenticated/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof AuthenticatedFitnessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clock': {
      id: '/_authenticated/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof AuthenticatedClockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/health-share/$token': {
      id: '/api/health-share/$token'
      path: '/api/health-share/$token'
      fullPath: '/api/health-share/$token'
      preLoaderRoute: typeof ApiHealthShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trackers/vitals': {
      id: '/_authenticated/trackers/vitals'
      path: '/trackers/vitals'
      fullPath: '/trackers/vitals'
      preLoaderRoute: typeof AuthenticatedTrackersVitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find/hospitals': {
      id: '/_authenticated/find/hospitals'
      path: '/find/hospitals'
      fullPath: '/find/hospitals'
      preLoaderRoute: typeof AuthenticatedFindHospitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedClockRoute: typeof AuthenticatedClockRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedFitnessRoute: typeof AuthenticatedFitnessRoute
  AuthenticatedHealthVaultRoute: typeof AuthenticatedHealthVaultRoute
  AuthenticatedHydrationRoute: typeof AuthenticatedHydrationRoute
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSleepRoute: typeof AuthenticatedSleepRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedFindHospitalsRoute: typeof AuthenticatedFindHospitalsRoute
  AuthenticatedTrackersVitalsRoute: typeof AuthenticatedTrackersVitalsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedClockRoute: AuthenticatedClockRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedFitnessRoute: AuthenticatedFitnessRoute,
  AuthenticatedHealthVaultRoute: AuthenticatedHealthVaultRoute,
  AuthenticatedHydrationRoute: AuthenticatedHydrationRoute,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSleepRoute: AuthenticatedSleepRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedFindHospitalsRoute: AuthenticatedFindHospitalsRoute,
  AuthenticatedTrackersVitalsRoute: AuthenticatedTrackersVitalsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFitnessSuggestionRoute: ApiFitnessSuggestionRoute,
  ApiMedverifyRoute: ApiMedverifyRoute,
  ApiNutritionRoute: ApiNutritionRoute,
  ApiSleepRoute: ApiSleepRoute,
  HealthShareTokenRoute: HealthShareTokenRoute,
  ApiHealthShareTokenRoute: ApiHealthShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
